Bestwon
DaITssu/daitssu-client pull request #1
Opened 2023-07-05 09:41 UTC by ChoiSangwon

## 리얼월드 (상원 ver)
- 메인화면 구현
- 상세페이지 구현
- 로그인 및 회원가입 구현

이정도까지만 구현해봤어요.
연습으로 한거니 코드 더러워도 봐줘.... next 13되면서 뭐이리 바뀐게 많아

전체프레임 다들 고생하십니다 ㅎㅎ

2023-07-05 12:19 UTC, aube-dev requested changes
너무 수고하셨어요! 몇 가지 코멘트 남겨놓았는데 한 번 참고해 주세요!

2023-07-05 12:19 UTC, aube-dev commented on src/components/Main/pagenations.tsx
> +  return <div>{renderPagination()}</div>;
🍌 불변성을 지키는 의미에서 `for` 대신 `.map`으로 바꾸면 어떨까요?
```typescript
return (
  <div>
    <ul className="pagination">
      {new Array(totalPages).fill(0).map((item, index) => (
        <li
          key={index}
          className={`page-item ${currentPage === index ? 'active' : ''}`}
        >
          <a
            className="page-link"
            onClick={() => {
              onPageChange(index);
            }
          >
            {index}
          </a>
        </li>
      ))}
    </ul>
  </div>
);

2023-07-05 12:19 UTC, aube-dev commented on src/components/login.tsx
> +  };
🍌 `async` 함수니까 `.then` 대신 `await`을 사용하면 어떨까요?
```typescript
const response = await login(email, password);
setUser(response.user);
router.replace('/');
```

2023-07-05 12:19 UTC, aube-dev commented on src/components/register.tsx
> +  };
🍌 async 함수니까 .then 대신 await을 사용하면 어떨까요?
```typescript
const response = await signup(username, email, password);
setUser(response.user);
router.replace('/');
```

2023-07-05 12:19 UTC, aube-dev commented on src/pages/article/[slug].page.tsx
> +      const data = await getArticleDetail(slug as String);
🍎 `String` 타입 말고 primitive인 `string` 타입을 사용해야 합니다!

2023-07-05 15:15 UTC, kweonsikyung commented
전체프레임팀은 다잇슈도 아니냐며... 우리빼고 회식한거 뭐냐며.... 그것빼고 참 조타......

2023-07-06 01:02 UTC, ChoiSangwon commented on src/pages/article/[slug].page.tsx
> +      const data = await getArticleDetail(slug as String);
앗.... 맞네

2023-07-06 01:03 UTC, ChoiSangwon commented on src/components/login.tsx
> +  };
이게 제가 보통 fetch를 사용하다보니 습관적으로 이런거 같네요 ㅎㅎ....

2023-07-06 01:07 UTC, ChoiSangwon commented on next.config.js
> +  reactStrictMode: false,
https://www.google.com/search?client=safari&rls=en&q=useEffect+%EB%91%90%EB%B2%88&ie=UTF-8&oe=UTF-8
https://stackoverflow.com/questions/60618844/react-hooks-useeffect-is-called-twice-even-if-an-empty-array-is-used-as-an-ar

그 개발하면서 useEffect가 두번씩 불러와지는거 때문에 껐습니다!
그래서 보통 개발할때에도 제가 많이 끄고했는데 이게 꺼도 괜찮은건가요..?

2023-07-06 01:07 UTC, ChoiSangwon commented on .gitignore
> +package-lock.json
넵

2023-07-06 01:07 UTC, ChoiSangwon commented on src/api/getArticleDetail.tsx
> +    console.log(response.data);
앗 알겠습니다!

2023-07-06 01:07 UTC, ChoiSangwon commented on src/api/getArticles.tsx
> +        offset: page * 10,
아 이건 생각 못했네요!

2023-07-06 05:50 UTC, aube-dev commented on next.config.js
> +  reactStrictMode: false,
useEffect가 2번 불러와지는 문제는 개발 모드인 경우에만 해당이라 실제 동작에는 영향이 없는데, 이거 때문에 strict mode를 끄기에는 strict mode의 장점(문제가 될 수 있는 부분(라이프사이클 등)을 더 엄격하게 체크해준다는 점)이 좀 있으니 아쉬울 것 같아서 말씀드린 거였어요! 어느 쪽이든 크게 달라지지는 않지만 strict mode가 있는 게 더 안심되지 않을까 싶어서요!

2023-07-10 03:13 UTC, JjungminLee commented on src/components/login.tsx
> +  const [password, setPassword] = useState('');
input state들은 반복되는게 많으니까 hooks->useInput을 만들어서 관리해보는거 어떨까요?!

2023-07-23 06:22 UTC, closed without merging