[#104] 홈화면 검색창 구현
DaITssu/daitssu-client pull request #124
Opened 2023-10-04 14:34 UTC by JooHui-void

## Issue

- Resolves #104

## Description

- 홈화면 검색창 제작
- style 변환 

만들다 보니까 community안에 있는 컴포넌트가 없어져서 커뮤니티 리스트를 넣지 못했는데 제가 만든 커뮤니티 합치는 pr 머지하면 들어오겠죠...??
## Check List

- [x]  PR 제목을 커밋 규칙에 맞게 작성
- [x]  PR에 해당되는 Issue를 연결 완료
- [x]  적절한 라벨 설정
- [x]  작업한 사람 모두를 Assign
- [x]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [x]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot
![image](https://github.com/DaITssu/daitssu-client/assets/69834729/6039c35b-d672-4d27-befa-7992708ac23e)

2023-10-05 10:13 UTC, SujinKim1127 requested changes
표시해드린부분 다 바꿔주세용

2023-10-05 10:13 UTC, SujinKim1127 commented on src/styles/constants/NoticeItem.style.ts
>    background: #d9d9d9;
공통색상으로 바꿔주세요!

2023-10-05 10:13 UTC, SujinKim1127 commented on src/components/Home/NoticeFunSystemTab/LineSearchBar/LineSearchBar.style.ts
> +  font-size: 16px;
여기도 공통색상이랑 공통 텍스트 스타일로 바꿔주세요!

2023-10-05 10:13 UTC, SujinKim1127 commented on src/components/Home/NoticeFunSystemTab/NoticeFunSystemTab.style.tsx
> +  ${(props) => (props.isSelected ? '#5EBEEB' : '#D9D9D9')};
여기도 공통색상으로 바꿔주세용

2023-10-05 10:36 UTC, halfmoon-mind commented on src/components/Home/NoticeFunSystemTab/NoticeFunSystemTab.style.tsx
> +  position: absolute;
absolute로 지정해야할까용?

2023-10-05 14:46 UTC, JooHui-void commented on src/components/Home/NoticeFunSystemTab/LineSearchBar/LineSearchBar.style.ts
> +  box-sizing : border-box;
알아보고 적용해놓겠습니다..!

2023-10-05 18:24 UTC, JooHui-void commented on src/components/Home/NoticeFunSystemTab/NoticeFunSystemTab.tsx
> +    </div>
확인했습니다!

2023-10-05 18:43 UTC, JooHui-void commented on src/styles/constants/NoticeItem.style.ts
>    background: #d9d9d9;
확인했습니다!!

2023-10-09 02:58 UTC, halfmoon-mind reviewed
보시고 피드백 해주세요!

2023-10-09 02:58 UTC, halfmoon-mind commented on src/components/Home/NoticeFunSystemTab/LineSearchBar/LineSearchBar.style.ts
> +  padding-bottom : 8px;
padding 값을 지정해주는건 어떤가요?
```suggestion
  padding: 0 16 8 16;
```

2023-10-09 02:58 UTC, halfmoon-mind commented on src/components/Home/NoticeFunSystemTab/NoticeFunSystemTab.style.tsx
이름 styles로 바꾸면 좋을 것 같아요!
저번에 얘기할 때 style -> styles로 통일하면 좋을 것 같다고 해서 동일하게 작업하는게 좋을 것 같아서요!
다른 부분에서도 수정 부탁드릴게요!

2023-10-09 02:58 UTC, halfmoon-mind commented on src/styles/constants/NoticeList.style.ts
>  export const NoticeListBox = styled.div`
지금 보니까 notice list 자체의 스타일은 src/styles/constants/NoticeList.style.ts 에 있는게 아니라 따로 Component 하위에 NoticeList에 있어야하지 않나용..?
공통으로 작업되야하는 부분이면 commons에 들어가고요!

2023-10-09 02:58 UTC, halfmoon-mind commented on src/components/notice/NoticeItem.tsx
> +        <styles.ViewIcon src= {viewIcon} width={18} height={18} alt={''}  />
alt 이름 써주세요

2023-11-07 05:38 UTC, JooHui-void commented on src/components/Home/NoticeFunSystemTab/NoticeFunSystemTab.style.tsx
확인했습니다!

2023-11-07 12:14 UTC, SujinKim1127 approved these changes

2023-11-07 12:17 UTC, merged