Sujin
DaITssu/daitssu-client pull request #2
Opened 2023-07-05 09:42 UTC by SujinKim1127

swagger에서 article api 연결하는부분까지 진행했습니다.
api 연결은 axios로 연결했습니다!!!

전체프레임팀 화이팅!!!

2023-07-05 12:42 UTC, aube-dev requested changes
정말 수고하셨습니다! 코멘트 몇 개 남겼는데 참고해 주세요!

2023-07-05 12:42 UTC, aube-dev commented on package.json
> +    "jotai": "^2.2.1",
🍎 버전은 `^`이나 `~` 없이 고정된 버전으로 추가해서 예상치 못한 문제를 방지하면 좋을 것 같아요!

2023-07-05 12:42 UTC, aube-dev commented on src/pages/MainHome.tsx
> +  ];
🍎 이 부분 타입 정의가 일반 array가 아닌 tuple로 되어 있는 것 같은데, 이러면 `Article.articles`의 길이가 1로 강제되는 상황이에요. 혹시 이게 의도가 맞는 걸까요? 그리고 `Article` 안에 `articles`라는 속성이 있는 것도 조금 이상해 보입니다! 아니라면 혹시 이런 타입 정의가 의도일까요?
```typescript
interface Article {
  slug: string;
  title: string;
  description: string;
  body: string;
  tagList: string[]; // 빈 배열로 되어 있던데 이 부분 의도도 궁금합니다!
  createdAt: string;
  updatedAt: string;
  favorited: boolean;
  favoritesCount: number;
  author: {
    username: string;
    bio: string;
    image: string;
    following: boolean;
  };
}

interface Articles {
  articles: Article[];
}
```

2023-07-05 12:42 UTC, aube-dev commented on src/pages/MainHome.tsx
> +  const arrayArticle = useRef<Article>();
이 ref는 사용하지 않는 게 혹시 맞을까요?

2023-07-05 12:42 UTC, aube-dev commented on src/pages/MainHome.tsx
> +  }
🍌 불필요한 console은 지우는 게 가독성에 도움이 될 것 같아요!

🥝 `articles.articles`가 존재할 때만 콘솔을 띄우고 싶은 거라면 맞는 코드지만, 그냥 띄우기만 하면 된다면 이렇게 해도 좋을 것 같습니다!
```suggestion
  console.log('articles', articles?.articles?.length);
```

2023-07-05 12:42 UTC, aube-dev commented on src/pages/MainHome.tsx
> +              : ''}
🍌 삼항 연산자를 nest하면 좀 복잡한데, 이렇게 optional chaining이랑 nullish coalescing operator를 이용하면 더 깔끔할 것 같아요!
```typescript
{articles?.articles?.map((item) => (
  <div className="article-preview" key={item.createdAt}>
    <div className="article-meta">
      <a href="profile.html">
        <img src={item.author.image} />
      </a>
      <div className="info">
        <a href="" className="author">
          {item.author.username}
        </a>
        <span className="date">January 20th</span>{/* 이 부분은 왜 `createdAt`을 format하지 않고 그냥 string으로 넣은 건지 궁금합니다! */}
      </div>
      <button className="btn btn-outline-primary btn-sm pull-xs-right">
        <i className="ion-heart"></i> {item.favoriteCount}
      </button>
    </div>
    <a href="" className="preview-link">
      <h1>{item.title}</h1>
      <p>{item.description}</p>
      <span>Read more...</span>
    </a>
  </div>
)) ?? null}
```

2023-07-05 12:42 UTC, aube-dev commented on src/pages/MainHome.tsx
> +              </div>
🥝 이렇게 관리하면 어떨까요?
```typescript
const TAGS = [
  {
    label: 'programming',
    url: '',
  },
  {
    label: 'javascript',
    url: '',
  },
  {
    label: 'emberjs',
    url: '',
  },
  {
    label: 'angularjs',
    url: '',
  },
  {
    label: 'react',
    url: '',
  },
  {
    label: 'mean',
    url: '',
  },
  {
    label: 'node',
    url: '',
  },
  {
    label: 'rails',
    url: '',
  },
] as const satisfies { label: string; url: string; }[];

const MainHome = () => {
  // ...
  return (
    // ...
    <div className="tag-list">
      {TAGS.map((tag) => (
        <a href={tag.url} className="tag-pill tag-default">
          {tag.label}
        </a>
      ))}
    </div>
  );
}
```

2023-07-06 06:26 UTC, SujinKim1127 commented on package.json
> +    "jotai": "^2.2.1",
아아 그렇군요!! 코멘트 감사합니다!!

2023-07-06 07:08 UTC, SujinKim1127 commented on src/pages/MainHome.tsx
> +  ];
헉 이부분은 받아오는 데이터 형식을 맞추려다보니 이렇게 된 것 같아요! 광서님이 작성해주신 코드가 제가 하려는 의도였습니다!
tagList는 배열로된 데이터를 받아오길래 `string[]` 으로 선언했는데 빈배열 선언할 필요없이 `string`으로 해도 됩니다!

2023-07-06 07:09 UTC, SujinKim1127 commented on src/pages/MainHome.tsx
> +  const arrayArticle = useRef<Article>();
아 넵 맞습니다
지운다는걸 깜빡했네요 ㅠㅠ

2023-07-06 07:31 UTC, SujinKim1127 commented on src/pages/MainHome.tsx
> +              : ''}
key를 item.createdAt 으로 하는 방법은 생각 못했는데 좋은 아이디어 배워갑니다 🥹
createdAt 부분은 Date 형식으로 수정하겠습니다!

2023-07-06 07:40 UTC, SujinKim1127 commented on src/pages/MainHome.tsx
> +              </div>
오...!!
`const Tags` 에서 마지막에 사용하신 `as const satisfies`은 어떤 역할을 하는건가요??

2023-07-10 03:05 UTC, JjungminLee commented
제가 comment를 달았는데 이게 pr에는 안떠서 ! 우선 너무 수고하셨고, get API들은 여러군데에서 쓰여서 (특히 아티클 조회) hooks폴더를 만들어서 hook으로 관리하시면 좋을 것 같아요! (useQuery이용!) 수고하셨습니당~!!

2023-07-20 01:29 UTC, closed without merging