feat : Navbar + Header작업
DaITssu/daitssu-client pull request #58
Opened 2023-08-29 23:36 UTC by JjungminLee

## Issue #48 

## Description
- navbar 및 header작업 

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-08-30 16:51 UTC, JjungminLee commented
- @halfmoon-mind  squaush merge 해서 다시 커밋해놨습니다. [7ffc9a4] <- 보시면 될 것 같아요.

2023-08-30 17:05 UTC, halfmoon-mind requested changes
머지 컨플릭트 해결해주세요

2023-08-30 17:05 UTC, halfmoon-mind commented on package.json
> +>>>>>>> c172480df5d75518ef4e2023b18f57d0db1c23fd
merge 하고 남은 흔적들 확인해주세요

2023-08-30 17:05 UTC, halfmoon-mind commented on tsconfig.json
> +>>>>>>> c172480df5d75518ef4e2023b18f57d0db1c23fd
동일합니다 확인해주세요

2023-08-31 02:38 UTC, halfmoon-mind approved these changes
머지 중간중간 안된 부분들 해결하고, 코멘트 남긴 부분들 해결 후에 머지 해주세요.

2023-08-31 02:38 UTC, halfmoon-mind commented on src/pages/notice/index.page.tsx
> +>>>>>>> c172480df5d75518ef4e2023b18f57d0db1c23fd
머지 해결 부탁드려요

2023-08-31 02:38 UTC, halfmoon-mind commented on src/pages/test/index.page.tsx
> +>>>>>>> c172480df5d75518ef4e2023b18f57d0db1c23fd
이부분도

2023-08-31 02:38 UTC, halfmoon-mind commented on package.json
> +    "recoil-persist": "^5.1.0",
꺽쇠 (^)로 말고 특정 버전 명시하도록 부탁드려요

2023-08-31 02:38 UTC, halfmoon-mind commented on src/pages/_app.page.tsx
> +>>>>>>> c172480df5d75518ef4e2023b18f57d0db1c23fd
해결 부탁드려요

2023-08-31 12:14 UTC, halfmoon-mind commented
Merge Conflict 관련된 부분 force push로 제가 해결했습니다.
force push로 작업되는 중에 커밋이나 파일, 커밋 누락된 부분 확인해주시고 다 확인하면 머지해주세요.

2023-08-31 12:19 UTC, JjungminLee commented
제가 한시간 전에 스쿼시 머지해서 35개 커밋 conflict해결했습니다. 머지할게요.

2023-08-31 12:20 UTC, merged