Community
DaITssu/daitssu-client pull request #92
Opened 2023-09-19 04:06 UTC by chan0310

## Issue

- Resolves #49 

## Description

- 커뮤니티 작성 페이지 오류 수정 및 기존 community 브랜치와 병합했습니다.

## Check List

- [ ]  PR 제목을 커밋 규칙에 맞게 작성
- [ ]  PR에 해당되는 Issue를 연결 완료
- [ ]  적절한 라벨 설정
- [ ]  작업한 사람 모두를 Assign
- [ ]  작업한 팀에게 Code Review 요청 (Reviewer 등록)
- [ ]  `main` 브랜치의 최신 상태를 반영하고 있는지 확인

## Screenshot

2023-09-25 14:21 UTC, halfmoon-mind commented
제가 추가적으로 main 브랜치 최신 반영하기 위해서 rebase 후 force push로 올렸습니다 참고해주세요!

2023-09-27 07:41 UTC, halfmoon-mind commented
@JooHui-void 현재 작업했을 때, 아무 문제 없었을까요?

2023-10-06 00:06 UTC, halfmoon-mind commented
> @halfmoon-mind 각자 만든 컴포넌트에서 꺠지는 부분이 생기는데 해결해주셨을 듯 합니다..!

dev로 돌렸을 때 문제가 발생할까요 아니면 storybook에서 발생할까요?

2023-10-07 05:50 UTC, SujinKim1127 requested changes
바꿔야하는부분 다 수정해주세요~

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/anouncement/SelectButton.tsx
> +  border: none;
공통색상으로 변경해주세요~

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/community/community_writing/ImageInputBox/ImageBox/ImageBox.styles.tsx
> +import { COLORS } from '../../../../styles/constants/colors';
```suggestion
import { COLORS } from '@/styles/constants/colors';
```

이걸로 바꿔주세요

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/community/community_writing/InputForm/TextForm/TextForm.styles.tsx
> +    font-size: 16px; /* 원하는 플레이스홀더 텍스트의 글씨 크기로 조정 */
공통 텍스트 스타일로 적용해주세요~

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/community/community_writing/InputForm/TitleForm/TitleForm.styles.tsx
> +    font-size: 20px; /* 원하는 플레이스홀더 텍스트의 글씨 크기로 조정 */
이미 input font-size가 20px 인데 placeholder에도 font-size를 지정하신 이유가 있나요??
그리고 공통 텍스트 스타일로 바꿔주세요!

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/community/community_writing/MainForm/SubSelectBox/SelectListBox/SelectListBox.styles.tsx
> +  font-size: 16px;
여기도 공통스타일로 적용해주세용

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/community/community_writing/MainForm/SubSelectBox/SelectListBox/SelectListBox.tsx
> +            cursor: "pointer"}}
스타일 내용이 길면 따로 빼서 만들어주시는것도 좋을것 같아요!!
그리고 공통 스타일 적용해주세요

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/community/info/CommunityInfo.style.ts
이 페이지 공통 컬러, 텍스트 스타일 적용안된거 적용하기

2023-10-07 05:50 UTC, SujinKim1127 commented on src/components/noticeInfo/NoticeInfo.tsx
오잉 이거 components/notice/info 안으로 다 옮겼는데 이게 여기 왜 있는거죵..?

2023-10-07 05:50 UTC, SujinKim1127 commented on src/styles/community/list/CommunityList.style.ts
이 페이지 전부 다 공통 색상, 텍스트 적용안된 부분이랑 텍스트 간격 맞춰주세요

2023-10-07 05:50 UTC, SujinKim1127 commented on src/styles/community/list/CommunityListItem.style.ts
여기도!!!!!

2023-10-31 12:54 UTC, halfmoon-mind approved these changes
머지하고 오류있으면 다시 수정해요

2023-11-15 01:08 UTC, SujinKim1127 approved these changes

2023-11-15 01:09 UTC, merged